version: '3'
services:
  web:
    platform: linux/amd64
    container_name: web
    image: leeseolhui/server-web
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    platform: linux/amd64
    container_name: nginx
    image: leeseolhui/server-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:33306
    environment:
      MYSQL_DATABASE: 'bbok'
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data: