version: '3'
services:
  web:
    container_name: web
    image: leeseolhui/server-web
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: leeseolhui/server-nginx
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
