# 로컬 개발 환경 구성
spring:
  datasource:
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

