# redis-server.yml
version: '7.0.12'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_docker
    hostname: redis_docker
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379